import { EditorView } from "@codemirror/view";
import { HighlightStyle, syntaxHighlighting } from "@codemirror/language";
import { tags } from "@lezer/highlight";

export const forgeTheme = EditorView.theme({
  "&": { backgroundColor: "#000000", color: "#D4D4D4", height: "100%" },
  ".cm-content": { caretColor: "#4F8CFF", fontFamily: "'JetBrains Mono', 'Fira Code', 'Cascadia Code', monospace", fontSize: "13px", padding: "16px" },
  ".cm-cursor": { borderLeftColor: "#4F8CFF", borderLeftWidth: "2px" },
  ".cm-selectionBackground, ::selection": { backgroundColor: "#335CFF55" },
  "&.cm-focused .cm-selectionBackground": { backgroundColor: "#335CFF77" },
  ".cm-gutters": { backgroundColor: "#000000", color: "#6B7280", border: "none" },
  ".cm-activeLine": { backgroundColor: "#111111" },
  ".cm-activeLineGutter": { backgroundColor: "#111111", color: "#FFFFFF", fontWeight: 600 },
  ".cm-scroller": { overflow: "auto", fontFamily: "'JetBrains Mono', 'Fira Code', 'Cascadia Code', monospace", fontSize: "13px" },
  ".cm-matchingBracket": { color: "#FFFFFF", backgroundColor: "rgba(79,140,255,.15)", outline: "1px solid rgba(79,140,255,.3)" },
  ".cm-searchMatch": { backgroundColor: "rgba(250,204,21,0.45) !important", color: "#000000 !important", borderRadius: "2px", outline: "1px solid #EAB308" },
  ".cm-searchMatch-selected": { backgroundColor: "#FACC15 !important", color: "#000000 !important", fontWeight: 700, borderRadius: "2px", boxShadow: "0 0 10px rgba(250,204,21,0.9)", outline: "2px solid #FEF08A" },
  ".cm-search": { backgroundColor: "#000000", borderBottom: "1px solid #222", padding: "8px", fontSize: "13px", fontFamily: "sans-serif" },
  ".cm-search input": { background: "#111", border: "1px solid #333", borderRadius: "4px", padding: "4px 8px", color: "#D4D4D4", outline: "none" },
  ".cm-search input:focus": { borderColor: "#4F8CFF" },
  ".cm-search button": { background: "#222", border: "none", borderRadius: "4px", padding: "4px 8px", color: "#D4D4D4", cursor: "pointer", fontSize: "12px" },
  ".cm-search button:hover": { background: "#333" },
  ".cm-search label": { color: "#6B7280", fontSize: "12px" },
  ".cm-scroller::-webkit-scrollbar": { width: "10px" },
  ".cm-scroller::-webkit-scrollbar-thumb": { background: "#333", borderRadius: "999px" },
  ".cm-scroller::-webkit-scrollbar-track": { background: "transparent" },
  ".cm-foldPlaceholder": { backgroundColor: "#111", color: "#6B7280", border: "none" },
});

export const forgeHighlight = syntaxHighlighting(
  HighlightStyle.define([
    { tag: tags.keyword, color: "#4F8CFF" },
    { tag: tags.definitionKeyword, color: "#4F8CFF" },
    { tag: tags.moduleKeyword, color: "#4F8CFF" },
    { tag: tags.controlKeyword, color: "#BB9AF7" },
    { tag: tags.operatorKeyword, color: "#4F8CFF" },
    { tag: tags.operator, color: "#89B4FA" },
    { tag: tags.regexp, color: "#F38BA8" },
    { tag: tags.string, color: "#A6E3A1" },
    { tag: tags.character, color: "#F9E2AF" },
    { tag: tags.number, color: "#F9E2AF" },
    { tag: tags.bool, color: "#F9E2AF" },
    { tag: tags.null, color: "#F9E2AF" },
    { tag: tags.atom, color: "#89B4FA" },
    { tag: tags.propertyName, color: "#89B4FA" },
    { tag: tags.attributeName, color: "#89B4FA" },
    { tag: tags.variableName, color: "#F5C2E7" },
    { tag: tags.typeName, color: "#F9E2AF" },
    { tag: tags.className, color: "#F9E2AF" },
    { tag: tags.self, color: "#F5C2E7" },
    { tag: tags.comment, color: "#6B7280", fontStyle: "italic" },
    { tag: tags.docComment, color: "#6B7280", fontStyle: "italic" },
    { tag: tags.meta, color: "#6B7280" },
    { tag: tags.separator, color: "#565F89" },
    { tag: tags.heading, color: "#4F8CFF", fontWeight: "bold" },
    { tag: tags.strong, color: "#D4D4D4", fontWeight: "bold" },
    { tag: tags.emphasis, color: "#D4D4D4", fontStyle: "italic" },
    { tag: tags.link, color: "#89B4FA" },
    { tag: tags.strikethrough, color: "#6B7280" },
    { tag: tags.deleted, color: "#F38BA8" },
    { tag: tags.inserted, color: "#A6E3A1" },
    { tag: tags.changed, color: "#F9E2AF" },
    { tag: tags.invalid, color: "#F38BA8" },
    { tag: tags.labelName, color: "#A6E3A1" },
    { tag: tags.namespace, color: "#BB9AF7" },
    { tag: tags.literal, color: "#F9E2AF" },
    { tag: tags.escape, color: "#F38BA8" },
  ])
);
