// Per-session JSONL storage — append-only session files with a metadata index.
//
// Layout:
//   ~/.forge-ade/sessions/<id>.jsonl      first line = session header, then entries
//   ~/.forge-ade/sessions/index.jsonl     one SessionMeta line per session (atomic rewrite)
//
// Legacy `~/.forge-ade/agent_sessions.json` (single monolithic file) is imported
// once on startup and then ignored.

import fs from "fs";
import path from "path";
import os from "os";
import type {
  AgentMessage,
  Session,
  SessionFileEntry,
  SessionMeta,
  TurnUsage,
} from "./types";
import { emptySession, DEFAULT_CONTEXT_WINDOW } from "./types";

const SCHEMA_VERSION = 1;

export function sessionsDir(dataDir?: string): string {
  const root = dataDir || path.join(os.homedir(), ".forge-ade");
  return path.join(root, "sessions");
}

function sessionPath(id: string, dir: string): string {
  // ids are generated by us (agent-<ts>-<rand>); sanitize defensively anyway
  const safe = id.replace(/[^a-zA-Z0-9._-]/g, "_");
  return path.join(dir, `${safe}.jsonl`);
}

function indexPath(dir: string): string {
  return path.join(dir, "index.jsonl");
}

// ---------------------------------------------------------------------------
// Header <-> meta conversion
// ---------------------------------------------------------------------------

interface StoredHeader {
  type: "session";
  version: number;
  id: string;
  name: string;
  role: string;
  projectFolder: string;
  dialect?: string | undefined;
  autoApprove?: boolean | undefined;
  customPrompt?: string | undefined;
  customRules?: string | undefined;
  modelOverride?: string | undefined;
  createdAt: number;
  updatedAt: number;
  summary?: string | undefined;
  observations?: { ts: number; summary: string }[] | undefined;
  todos?: { id: string; title: string; completed: boolean; active?: boolean | undefined }[] | undefined;
  totalUsage?: { promptTokens: number; completionTokens: number; requests: number } | undefined;
  state?: string | undefined;
  contextWindow?: number | undefined;
  lastUsage?: TurnUsage | undefined;
}

function headerFromSession(s: Session): StoredHeader {
  return {
    type: "session",
    version: SCHEMA_VERSION,
    id: s.id,
    name: s.name,
    role: s.role,
    projectFolder: s.projectFolder,
    dialect: s.dialect,
    autoApprove: s.autoApprove,
    customPrompt: s.customPrompt,
    customRules: s.customRules,
    modelOverride: s.modelOverride,
    createdAt: s.createdAt,
    updatedAt: s.updatedAt,
    summary: s.summary,
    observations: s.observations,
    todos: s.todos,
    totalUsage: s.totalUsage,
    contextWindow: s.contextWindow,
    lastUsage: s.lastUsage,
    state: s.state === "running" || s.state === "awaiting_approval" || s.state === "awaiting_input"
      ? "idle" // crashed/restarted daemon never resumes as mid-turn
      : s.state,
  };
}

function metaOf(header: StoredHeader): SessionMeta {
  return {
    id: header.id,
    name: header.name,
    role: header.role,
    projectFolder: header.projectFolder,
    dialect: header.dialect || "",
    autoApprove: header.autoApprove || false,
    createdAt: header.createdAt,
    updatedAt: header.updatedAt,
    messageCount: 0,
    lastMessagePreview: "",
    state: (header.state as Session["state"]) || "idle",
    contextWindow: header.contextWindow ?? DEFAULT_CONTEXT_WINDOW,
    lastUsage: header.lastUsage,
  };
}

// ---------------------------------------------------------------------------
// Store
// ---------------------------------------------------------------------------

export class SessionStore {
  private dir: string;
  private headers = new Map<string, StoredHeader>();
  private counts = new Map<string, { count: number; preview: string }>();

  constructor(dataDir?: string) {
    this.dir = sessionsDir(dataDir);
    fs.mkdirSync(this.dir, { recursive: true });
    this.importLegacyIfNeeded();
    this.loadIndex();
  }

  // -- legacy import ---------------------------------------------------------

  private importLegacyIfNeeded(): void {
    const legacyFile = path.join(path.dirname(this.dir), "agent_sessions.json");
    if (!fs.existsSync(legacyFile)) return;
    if (fs.existsSync(indexPath(this.dir))) return; // already migrated
    try {
      const raw = JSON.parse(fs.readFileSync(legacyFile, "utf-8"));
      if (!Array.isArray(raw)) return;
      for (const old of raw) {
        if (!old?.id) continue;
        const created = typeof old.createdAt === "number" ? old.createdAt : Date.now();
        const s = emptySession({
          id: String(old.id),
          name: String(old.name || "Agent Session"),
          role: String(old.role || "coding"),
          projectFolder: String(old.projectFolder || process.cwd()),
          createdAt: created,
        });
        s.customPrompt = old.customPrompt;
        s.customRules = old.customRules;
        s.autoApprove = Boolean(old.autoApprove);
        s.messages = Array.isArray(old.messages)
          ? old.messages.map((m: any, i: number) => ({
              id: String(m.id ?? `${s.id}-m${i}`),
              role: m.role,
              content: Array.isArray(m.content) ? m.content : [{ type: "text", text: String(m.content ?? "") }],
              timestamp: String(m.timestamp ?? new Date(created).toISOString()),
            }))
          : [];
        this.createFileFor(s);
      }
      fs.renameSync(legacyFile, `${legacyFile}.migrated`);
    } catch (err) {
      console.error("[agent-store] legacy import failed:", err);
    }
  }

  // -- index -----------------------------------------------------------------

  private loadIndex(): void {
    const idx = indexPath(this.dir);
    let metas: SessionMeta[] = [];
    try {
      const lines = fs.readFileSync(idx, "utf-8").split("\n").filter(Boolean);
      for (const line of lines) {
        try {
          metas.push(JSON.parse(line));
        } catch {}
      }
    } catch {}
    const seen = new Set<string>();
    for (const m of metas) {
      if (seen.has(m.id)) continue;
      seen.add(m.id);
      const file = sessionPath(m.id, this.dir);
      if (!fs.existsSync(file)) continue;
      try {
        const header = JSON.parse(fs.readFileSync(file, "utf-8").split("\n", 1)[0]);
        this.headers.set(m.id, header);
        // Recount from the file tail so index drift self-heals.
        const { count, preview } = this.scanMessages(file);
        this.counts.set(m.id, { count, preview });
      } catch {}
    }
    // Pick up session files missing from the index (crash between writes).
    for (const f of fs.readdirSync(this.dir)) {
      if (!f.endsWith(".jsonl") || f === "index.jsonl") continue;
      const id = f.slice(0, -".jsonl".length);
      if (seen.has(id)) continue;
      try {
        const header: StoredHeader = JSON.parse(fs.readFileSync(sessionPath(id, this.dir), "utf-8").split("\n", 1)[0]);
        this.headers.set(id, header);
        const { count, preview } = this.scanMessages(sessionPath(id, this.dir));
        this.counts.set(id, { count, preview });
        this.persistMeta(id);
      } catch {}
    }
  }

  private scanMessages(file: string): { count: number; preview: string } {
    let count = 0;
    let preview = "";
    try {
      const content = fs.readFileSync(file, "utf-8");
      for (const line of content.split("\n")) {
        if (!line) continue;
        let entry: any;
        try {
          entry = JSON.parse(line);
        } catch {
          continue;
        }
        if (entry?.type !== "message" || !entry.message) continue;
        count++;
        const blocks: any[] = entry.message.content || [];
        const text = blocks.find((b: any) => b.type === "text")?.text
          ?? blocks.find((b: any) => b.type === "tool_call")?.name
          ?? "";
        if (text && !preview) preview = String(text).slice(0, 120);
        else if (text) preview = String(text).slice(0, 120);
      }
    } catch {}
    return { count, preview };
  }

  /** Atomic index rewrite for one session's meta line. */
  persistMeta(id: string): void {
    const header = this.headers.get(id);
    if (!header) return;
    const { count, preview } = this.counts.get(id) || { count: 0, preview: "" };
    const meta: SessionMeta = {
      ...metaOf(header),
      messageCount: count,
      lastMessagePreview: preview,
      updatedAt: header.updatedAt,
    };
    const idx = indexPath(this.dir);
    let lines: string[] = [];
    try {
      lines = fs.readFileSync(idx, "utf-8").split("\n").filter(Boolean);
    } catch {}
    const kept = lines.filter((l) => {
      try {
        return JSON.parse(l).id !== id;
      } catch {
        return true;
      }
    });
    kept.push(JSON.stringify(meta));
    const tmp = `${idx}.tmp`;
    fs.writeFileSync(tmp, kept.join("\n") + "\n", "utf-8");
    fs.renameSync(tmp, idx);
  }

  removeMeta(id: string): void {
    this.headers.delete(id);
    this.counts.delete(id);
    const idx = indexPath(this.dir);
    try {
      const lines = fs.readFileSync(idx, "utf-8").split("\n").filter(Boolean);
      const kept = lines.filter((l) => {
        try {
          return JSON.parse(l).id !== id;
        } catch {
          return true;
        }
      });
      const tmp = `${idx}.tmp`;
      fs.writeFileSync(tmp, kept.join("\n") + "\n", "utf-8");
      fs.renameSync(tmp, idx);
    } catch {}
  }

  // -- session files -----------------------------------------------------------

  createFileFor(s: Session): void {
    const file = sessionPath(s.id, this.dir);
    const header = headerFromSession(s);
    this.headers.set(s.id, header);
    this.counts.set(s.id, { count: 0, preview: "" });
    fs.writeFileSync(file, JSON.stringify(header) + "\n", "utf-8");
    this.persistMeta(s.id);
  }

  has(id: string): boolean {
    return this.headers.has(id);
  }

  /** Loads full session incl. all messages (header + replayed entries). */
  load(id: string): Session | null {
    const header = this.headers.get(id);
    const file = sessionPath(id, this.dir);
    if (!header || !fs.existsSync(file)) return null;
    const messages: AgentMessage[] = [];
    let summary: string | undefined;
    let keptFrom: string | null = null;
    let parentId: string | null = null;
    try {
      const content = fs.readFileSync(file, "utf-8");
      for (const line of content.split("\n")) {
        if (!line) continue;
        let entry: any;
        try {
          entry = JSON.parse(line);
        } catch {
          continue;
        }
        switch (entry.type) {
          case "message":
            messages.push(entry.message as AgentMessage);
            parentId = entry.id;
            break;
          case "compaction":
            // Drop everything before the compaction point; keep the digest.
            {
              const idx = messages.findIndex((m) => m.id === entry.keptFromMessageId);
              if (idx >= 0) messages.splice(0, idx);
              else messages.length = 0;
            }
            summary = entry.summary;
            keptFrom = entry.keptFromMessageId;
            break;
        }
      }
    } catch (err) {
      console.error(`[agent-store] failed to load ${id}:`, err);
    }
    void keptFrom;
    void parentId;
    const { count, preview } = this.counts.get(id) || { count: messages.length, preview: "" };
    return {
      ...emptySession({
        id: header.id,
        name: header.name,
        role: header.role,
        projectFolder: header.projectFolder,
        createdAt: header.createdAt,
      }),
      dialect: header.dialect || "",
      autoApprove: header.autoApprove || false,
      customPrompt: header.customPrompt,
      customRules: header.customRules,
      modelOverride: header.modelOverride,
      summary,
      observations: header.observations || [],
      todos: header.todos || [],
      totalUsage: header.totalUsage || { promptTokens: 0, completionTokens: 0, requests: 0 },
      state: (header.state as Session["state"]) || "idle",
      contextWindow: header.contextWindow ?? DEFAULT_CONTEXT_WINDOW,
      lastUsage: header.lastUsage,
      updatedAt: header.updatedAt,
      messages,
      messageCount: Math.max(count, messages.length),
      lastMessagePreview: preview,
    };
  }

  listMetas(): SessionMeta[] {
    const metas: SessionMeta[] = [];
    for (const [id, header] of this.headers) {
      const { count, preview } = this.counts.get(id) || { count: 0, preview: "" };
      metas.push({ ...metaOf(header), messageCount: count, lastMessagePreview: preview });
    }
    metas.sort((a, b) => b.updatedAt - a.updatedAt);
    return metas;
  }

  appendMessage(id: string, msg: AgentMessage, opts?: { touchUpdatedAt?: boolean }): void {
    const header = this.headers.get(id);
    if (!header) return;
    const persisted: AgentMessage = { ...msg };
    delete persisted.state; // streaming marker is ephemeral
    const entry: SessionFileEntry = {
      type: "message",
      id: `e-${Date.now()}-${Math.random().toString(36).slice(2, 7)}`,
      parentId: null,
      timestamp: new Date().toISOString(),
      message: persisted,
    };
    const line = JSON.stringify(entry) + "\n";
    fs.appendFileSync(sessionPath(id, this.dir), line, "utf-8");
    if (opts?.touchUpdatedAt !== false) header.updatedAt = Date.now();
    const c = this.counts.get(id) || { count: 0, preview: "" };
    c.count += 1;
    const text = persisted.content.find((b) => b.type === "text")?.text
      ?? persisted.content.find((b) => b.type === "tool_call")?.name
      ?? "";
    if (text) c.preview = String(text).slice(0, 120);
    this.counts.set(id, c);
    // Coalesce meta rewrites at the call site for hot loops; cheap enough here.
    this.persistMeta(id);
  }

  appendCompaction(id: string, summary: string, keptFromMessageId: string): void {
    const header = this.headers.get(id);
    if (!header) return;
    const entry: SessionFileEntry = {
      type: "compaction",
      id: `e-${Date.now()}-${Math.random().toString(36).slice(2, 7)}`,
      parentId: null,
      timestamp: new Date().toISOString(),
      summary,
      keptFromMessageId,
    };
    fs.appendFileSync(sessionPath(id, this.dir), JSON.stringify(entry) + "\n", "utf-8");
  }

  /** Rewrites the header line in place (metadata-only change). */
  updateHeader(id: string, patch: Partial<StoredHeader>): void {
    const header = this.headers.get(id);
    if (!header) return;
    Object.assign(header, patch);
    header.updatedAt = Date.now();
    const file = sessionPath(id, this.dir);
    try {
      const content = fs.readFileSync(file, "utf-8");
      const rest = content.slice(content.indexOf("\n") + 1);
      const tmp = `${file}.tmp`;
      fs.writeFileSync(tmp, JSON.stringify(header) + "\n" + rest, "utf-8");
      fs.renameSync(tmp, file);
      this.persistMeta(id);
    } catch (err) {
      console.error(`[agent-store] header update failed for ${id}:`, err);
    }
  }

  deleteSession(id: string): void {
    try {
      fs.rmSync(sessionPath(id, this.dir), { force: true });
    } catch {}
    this.removeMeta(id);
  }

  clearSession(id: string): void {
    const header = this.headers.get(id);
    if (!header) return;
    header.summary = undefined;
    header.observations = [];
    const file = sessionPath(id, this.dir);
    fs.writeFileSync(file, JSON.stringify(header) + "\n", "utf-8");
    this.counts.set(id, { count: 0, preview: "" });
    this.persistMeta(id);
  }
}
