// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {terminal} from '../models';
import {git} from '../models';
import {workspace} from '../models';
import {main} from '../models';
import {ai} from '../models';
import {search} from '../models';
import {context} from '../models';

export function CloseTerminal(arg1:string):Promise<void>;

export function CloseWorkspace():Promise<void>;

export function CreateFile(arg1:string):Promise<void>;

export function CreateTerminal(arg1:string,arg2:string,arg3:string):Promise<terminal.Session>;

export function DeleteFile(arg1:string):Promise<void>;

export function DiscoverRepos():Promise<void>;

export function ExpandPath(arg1:string):Promise<string>;

export function GetBranches(arg1:string):Promise<Array<git.Branch>>;

export function GetCommits(arg1:string,arg2:number):Promise<Array<git.Commit>>;

export function GetCurrentWorkspace():Promise<workspace.Workspace>;

export function GetFileTree(arg1:number):Promise<string>;

export function GetRecentProjects():Promise<Array<workspace.RecentEntry>>;

export function GetRepoStatus():Promise<Record<string, Array<git.StatusEntry>>>;

export function GetWorkspaceInfo():Promise<main.WorkspaceInfo>;

export function GitCommit(arg1:string,arg2:string):Promise<void>;

export function GitRunCommand(arg1:string,arg2:string):Promise<string>;

export function GitStage(arg1:string,arg2:Array<string>):Promise<void>;

export function GitStageAll(arg1:string):Promise<void>;

export function GitUnstage(arg1:string,arg2:Array<string>):Promise<void>;

export function ListAgents():Promise<Array<ai.Agent>>;

export function ListDirectory(arg1:string):Promise<string>;

export function ListTerminals():Promise<Array<terminal.Session>>;

export function OpenFolder(arg1:string):Promise<workspace.Workspace>;

export function OpenFolderDialog():Promise<string>;

export function OpenWorkspace(arg1:string):Promise<workspace.Workspace>;

export function OpenWorkspaceDialog():Promise<string>;

export function PinRecent(arg1:string,arg2:boolean):Promise<void>;

export function ReadFile(arg1:string):Promise<string>;

export function RemoveRecent(arg1:string):Promise<void>;

export function RenameFile(arg1:string,arg2:string):Promise<void>;

export function ResizeTerminal(arg1:string,arg2:number,arg3:number):Promise<void>;

export function SaveWorkspace():Promise<void>;

export function SaveWorkspaceAs(arg1:string):Promise<void>;

export function SearchContent(arg1:string,arg2:number):Promise<Array<search.RankedResult>>;

export function SearchFilename(arg1:string,arg2:number):Promise<Array<search.RankedResult>>;

export function Shutdown():Promise<void>;

export function StartAgent(arg1:string,arg2:string,arg3:string):Promise<ai.Agent>;

export function Startup(arg1:context.Context):Promise<void>;

export function StopAgent(arg1:string):Promise<void>;

export function Subscribe(arg1:string):Promise<void>;

export function ToggleHiddenFiles():Promise<boolean>;

export function WriteFile(arg1:string,arg2:string):Promise<void>;

export function WriteTerminal(arg1:string,arg2:string):Promise<void>;
