// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';
import {terminal} from '../models';
import {agent} from '../models';
import {index} from '../models';
import {workspace} from '../models';
import {git} from '../models';
import {llm} from '../models';
import {mcp} from '../models';
import {skills} from '../models';
import {search} from '../models';
import {context} from '../models';

export function AddFolderToWorkspace(arg1:string):Promise<void>;

export function ApplyAgentDefinitionToSession(arg1:string,arg2:string):Promise<void>;

export function BrowserOpenURL(arg1:string):Promise<void>;

export function CheckSyntax(arg1:string,arg2:string):Promise<Array<main.SyntaxDiagnostic>>;

export function CloseWorkspace():Promise<void>;

export function CopyFile(arg1:string,arg2:string):Promise<void>;

export function CopyPath(arg1:string,arg2:string):Promise<void>;

export function CreateAIAgent(arg1:string,arg2:string,arg3:string):Promise<terminal.Session>;

export function CreateAgentSession(arg1:string,arg2:string,arg3:string):Promise<agent.Session>;

export function CreateAgentSessionFromDefinition(arg1:string,arg2:string):Promise<agent.Session>;

export function CreateFile(arg1:string):Promise<void>;

export function CreateFolder(arg1:string):Promise<void>;

export function CreateShell(arg1:string,arg2:string):Promise<terminal.Session>;

export function DeleteAgentDefinition(arg1:string):Promise<void>;

export function DeleteAgentSession(arg1:string):Promise<void>;

export function DeleteFile(arg1:string):Promise<void>;

export function DeleteMCPServer(arg1:string):Promise<void>;

export function ExpandPath(arg1:string):Promise<string>;

export function FetchProviderModels(arg1:string,arg2:string):Promise<Array<string>>;

export function FindSymbol(arg1:string):Promise<Array<index.Symbol>>;

export function FormatCode(arg1:string,arg2:string):Promise<string>;

export function GenerateAICommitMessage(arg1:string,arg2:string,arg3:string,arg4:string):Promise<string>;

export function GetAgentSession(arg1:string):Promise<agent.Session>;

export function GetClipboardFiles():Promise<Array<string>>;

export function GetCompletion(arg1:string,arg2:string):Promise<Array<index.Symbol>>;

export function GetCurrentWorkspace():Promise<workspace.Workspace>;

export function GetExports(arg1:string):Promise<Array<index.Export>>;

export function GetFileTree(arg1:number):Promise<string>;

export function GetGitBranches(arg1:string):Promise<Array<string>>;

export function GetGitCommitBody(arg1:string,arg2:string):Promise<string>;

export function GetGitCommitDiff(arg1:string,arg2:string):Promise<string>;

export function GetGitCommitFileDiff(arg1:string,arg2:string,arg3:string):Promise<string>;

export function GetGitCommitGraph(arg1:string,arg2:number,arg3:number,arg4:string):Promise<git.CommitGraphResult>;

export function GetGitConflictStageContent(arg1:string,arg2:string,arg3:number):Promise<string>;

export function GetGitFileContentAtCommit(arg1:string,arg2:string,arg3:string):Promise<string>;

export function GetGitFileDiff(arg1:string,arg2:string):Promise<string>;

export function GetGitFileDiffHunks(arg1:string,arg2:string):Promise<Array<git.DiffHunk>>;

export function GetGitStatus(arg1:string):Promise<git.GitStatusResult>;

export function GetHomeDir():Promise<string>;

export function GetImports(arg1:string):Promise<Array<index.Import>>;

export function GetLLMConfig():Promise<llm.Profile>;

export function GetMembers(arg1:string,arg2:string):Promise<Array<index.Symbol>>;

export function GetOutline(arg1:string):Promise<Array<index.Symbol>>;

export function GetProviderProfiles():Promise<Array<llm.ProviderProfile>>;

export function GetRecentProjects():Promise<Array<workspace.RecentEntry>>;

export function GetSymbols():Promise<Array<index.Symbol>>;

export function GitCommit(arg1:string,arg2:string):Promise<void>;

export function GitDiscard(arg1:string,arg2:Array<string>):Promise<void>;

export function GitFetch(arg1:string):Promise<string>;

export function GitMerge(arg1:string,arg2:string,arg3:boolean,arg4:boolean):Promise<string>;

export function GitPush(arg1:string):Promise<void>;

export function GitResolveConflict(arg1:string,arg2:string,arg3:string):Promise<void>;

export function GitStage(arg1:string,arg2:Array<string>):Promise<void>;

export function GitUnstage(arg1:string,arg2:Array<string>):Promise<void>;

export function IndexStatus():Promise<Record<string, any>>;

export function IsDir(arg1:string):Promise<boolean>;

export function ListAIAgents():Promise<Array<terminal.Session>>;

export function ListAgentDefinitions():Promise<Array<agent.AgentDefinition>>;

export function ListAgentSessions():Promise<Array<agent.Session>>;

export function ListAgentSessionsForFolder(arg1:string):Promise<Array<agent.Session>>;

export function ListConnectedMCPTools():Promise<Array<mcp.Tool>>;

export function ListDirectory(arg1:string):Promise<string>;

export function ListLLMProviders():Promise<Array<llm.ProviderConfig>>;

export function ListMCPServers():Promise<Array<mcp.ServerConfig>>;

export function ListMCPTools():Promise<Array<mcp.Tool>>;

export function ListSessions():Promise<Array<terminal.Session>>;

export function ListShells():Promise<Array<terminal.Session>>;

export function ListSkills():Promise<Array<skills.Skill>>;

export function MoveFile(arg1:string,arg2:string):Promise<void>;

export function OpenFileDialog():Promise<string>;

export function OpenFolder(arg1:string):Promise<workspace.Workspace>;

export function OpenFolderDialog():Promise<string>;

export function OpenInFinder(arg1:string):Promise<void>;

export function OpenNewWindow(arg1:string):Promise<void>;

export function OpenWorkspace(arg1:string):Promise<workspace.Workspace>;

export function OpenWorkspaceDialog():Promise<string>;

export function PinRecent(arg1:string,arg2:boolean):Promise<void>;

export function ReadFile(arg1:string):Promise<string>;

export function ReadFileBase64(arg1:string):Promise<string>;

export function ReconnectMCP():Promise<void>;

export function RemoveFolderFromWorkspace(arg1:string):Promise<void>;

export function RemoveRecent(arg1:string):Promise<void>;

export function RenameFile(arg1:string,arg2:string):Promise<void>;

export function RenameSession(arg1:string,arg2:string):Promise<void>;

export function ResizeSession(arg1:string,arg2:number,arg3:number):Promise<void>;

export function ResolvePath(arg1:string):Promise<string>;

export function RespondAgentApproval(arg1:string,arg2:boolean,arg3:boolean):Promise<void>;

export function RespondAgentAsk(arg1:string,arg2:Record<string, any>):Promise<void>;

export function RevertGitHunk(arg1:string,arg2:string,arg3:number):Promise<void>;

export function SaveAgentDefinition(arg1:agent.AgentDefinition):Promise<agent.AgentDefinition>;

export function SaveLLMProfile(arg1:string,arg2:string,arg3:string,arg4:string):Promise<void>;

export function SaveMCPServer(arg1:mcp.ServerConfig):Promise<mcp.ServerConfig>;

export function SaveProviderProfiles(arg1:Array<llm.ProviderProfile>):Promise<void>;

export function SaveWorkspace():Promise<void>;

export function SaveWorkspaceAs(arg1:string):Promise<void>;

export function SaveWorkspaceDialog():Promise<string>;

export function SearchContent(arg1:string,arg2:number):Promise<Array<search.RankedResult>>;

export function SearchContentWithOptions(arg1:search.SearchOptions):Promise<Array<search.RankedResult>>;

export function SearchFilename(arg1:string,arg2:number):Promise<Array<search.RankedResult>>;

export function SearchFilenameWithOptions(arg1:search.SearchOptions):Promise<Array<search.RankedResult>>;

export function SearchIndexSymbols(arg1:string):Promise<Array<index.Symbol>>;

export function SearchReplaceAll(arg1:search.ReplaceOptions):Promise<search.ReplaceResult>;

export function SearchSymbols(arg1:string,arg2:number):Promise<Array<search.RankedResult>>;

export function SearchSymbolsWithOptions(arg1:search.SearchOptions):Promise<Array<search.RankedResult>>;

export function SendAgentMessage(arg1:string,arg2:string,arg3:Array<string>):Promise<void>;

export function SetActiveModel(arg1:string,arg2:string):Promise<void>;

export function SetAgentAutoApprove(arg1:string,arg2:boolean):Promise<void>;

export function SetAgentDialect(arg1:string,arg2:string):Promise<void>;

export function Shutdown():Promise<void>;

export function Startup(arg1:context.Context):Promise<void>;

export function StopAgentTurn(arg1:string):Promise<void>;

export function StopSession(arg1:string):Promise<void>;

export function Subscribe(arg1:string):Promise<void>;

export function ToggleAgentTask(arg1:string,arg2:string,arg3:boolean):Promise<void>;

export function ToggleHiddenFiles():Promise<boolean>;

export function UpdateAgentSession(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string):Promise<agent.Session>;

export function WriteFile(arg1:string,arg2:string):Promise<void>;

export function WriteSession(arg1:string,arg2:string):Promise<void>;
