// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {terminal} from '../models';
import {git} from '../models';
import {workspace} from '../models';
import {main} from '../models';
import {search} from '../models';
import {context} from '../models';

export function ClearDiffCache():Promise<void>;

export function CloseWorkspace():Promise<void>;

export function CopyFile(arg1:string,arg2:string):Promise<void>;

export function CreateAIAgent(arg1:string,arg2:string,arg3:string):Promise<terminal.Session>;

export function CreateFile(arg1:string):Promise<void>;

export function CreateShell(arg1:string,arg2:string):Promise<terminal.Session>;

export function DeleteFile(arg1:string):Promise<void>;

export function DiscoverRepos():Promise<void>;

export function ExpandPath(arg1:string):Promise<string>;

export function GetBranches(arg1:string):Promise<Array<git.Branch>>;

export function GetCommitDetail(arg1:string,arg2:string):Promise<string>;

export function GetCommitGraph(arg1:string,arg2:number):Promise<Array<git.CommitGraphEntry>>;

export function GetCommits(arg1:string,arg2:number):Promise<Array<git.Commit>>;

export function GetCurrentWorkspace():Promise<workspace.Workspace>;

export function GetDiffForOpenFiles(arg1:string,arg2:Array<string>):Promise<Record<string, git.FileDiff>>;

export function GetFileDiff(arg1:string,arg2:string):Promise<git.FileDiff>;

export function GetFileTree(arg1:number):Promise<string>;

export function GetFsChangeCount():Promise<number>;

export function GetHomeDir():Promise<string>;

export function GetRecentProjects():Promise<Array<workspace.RecentEntry>>;

export function GetRelPath(arg1:string):Promise<string>;

export function GetRepoRoot(arg1:string):Promise<string>;

export function GetRepoStatus():Promise<Record<string, Array<git.StatusEntry>>>;

export function GetWorkspaceInfo():Promise<main.WorkspaceInfo>;

export function GitCommit(arg1:string,arg2:string):Promise<void>;

export function GitRunCommand(arg1:string,arg2:string):Promise<string>;

export function GitStage(arg1:string,arg2:Array<string>):Promise<void>;

export function GitStageAll(arg1:string):Promise<void>;

export function GitUnstage(arg1:string,arg2:Array<string>):Promise<void>;

export function IsDir(arg1:string):Promise<boolean>;

export function ListAIAgents():Promise<Array<terminal.Session>>;

export function ListDirectory(arg1:string):Promise<string>;

export function ListSessions():Promise<Array<terminal.Session>>;

export function ListShells():Promise<Array<terminal.Session>>;

export function MoveFile(arg1:string,arg2:string):Promise<void>;

export function OpenFileDialog():Promise<string>;

export function OpenFolder(arg1:string):Promise<workspace.Workspace>;

export function OpenFolderDialog():Promise<string>;

export function OpenInFinder(arg1:string):Promise<void>;

export function OpenWorkspace(arg1:string):Promise<workspace.Workspace>;

export function OpenWorkspaceDialog():Promise<string>;

export function PinRecent(arg1:string,arg2:boolean):Promise<void>;

export function ReadFile(arg1:string):Promise<string>;

export function ReadFileBase64(arg1:string):Promise<string>;

export function RemoveRecent(arg1:string):Promise<void>;

export function RenameFile(arg1:string,arg2:string):Promise<void>;

export function RenameSession(arg1:string,arg2:string):Promise<void>;

export function ResizeSession(arg1:string,arg2:number,arg3:number):Promise<void>;

export function SaveWorkspace():Promise<void>;

export function SaveWorkspaceAs(arg1:string):Promise<void>;

export function SearchContent(arg1:string,arg2:number):Promise<Array<search.RankedResult>>;

export function SearchFilename(arg1:string,arg2:number):Promise<Array<search.RankedResult>>;

export function Shutdown():Promise<void>;

export function StageDiffHunk(arg1:string,arg2:string,arg3:number):Promise<void>;

export function Startup(arg1:context.Context):Promise<void>;

export function StopSession(arg1:string):Promise<void>;

export function Subscribe(arg1:string):Promise<void>;

export function ToggleHiddenFiles():Promise<boolean>;

export function WriteFile(arg1:string,arg2:string):Promise<void>;

export function WriteSession(arg1:string,arg2:string):Promise<void>;
