// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CloseWorkspace() {
  return window['go']['main']['App']['CloseWorkspace']();
}

export function CreateAIAgent(arg1, arg2, arg3) {
  return window['go']['main']['App']['CreateAIAgent'](arg1, arg2, arg3);
}

export function CreateFile(arg1) {
  return window['go']['main']['App']['CreateFile'](arg1);
}

export function CreateShell(arg1, arg2) {
  return window['go']['main']['App']['CreateShell'](arg1, arg2);
}

export function DeleteFile(arg1) {
  return window['go']['main']['App']['DeleteFile'](arg1);
}

export function DiscoverRepos() {
  return window['go']['main']['App']['DiscoverRepos']();
}

export function ExpandPath(arg1) {
  return window['go']['main']['App']['ExpandPath'](arg1);
}

export function GetBranches(arg1) {
  return window['go']['main']['App']['GetBranches'](arg1);
}

export function GetCommits(arg1, arg2) {
  return window['go']['main']['App']['GetCommits'](arg1, arg2);
}

export function GetCurrentWorkspace() {
  return window['go']['main']['App']['GetCurrentWorkspace']();
}

export function GetFileTree(arg1) {
  return window['go']['main']['App']['GetFileTree'](arg1);
}

export function GetFsChangeCount() {
  return window['go']['main']['App']['GetFsChangeCount']();
}

export function GetRecentProjects() {
  return window['go']['main']['App']['GetRecentProjects']();
}

export function GetRepoStatus() {
  return window['go']['main']['App']['GetRepoStatus']();
}

export function GetWorkspaceInfo() {
  return window['go']['main']['App']['GetWorkspaceInfo']();
}

export function GitCommit(arg1, arg2) {
  return window['go']['main']['App']['GitCommit'](arg1, arg2);
}

export function GitRunCommand(arg1, arg2) {
  return window['go']['main']['App']['GitRunCommand'](arg1, arg2);
}

export function GitStage(arg1, arg2) {
  return window['go']['main']['App']['GitStage'](arg1, arg2);
}

export function GitStageAll(arg1) {
  return window['go']['main']['App']['GitStageAll'](arg1);
}

export function GitUnstage(arg1, arg2) {
  return window['go']['main']['App']['GitUnstage'](arg1, arg2);
}

export function ListAIAgents() {
  return window['go']['main']['App']['ListAIAgents']();
}

export function ListDirectory(arg1) {
  return window['go']['main']['App']['ListDirectory'](arg1);
}

export function ListSessions() {
  return window['go']['main']['App']['ListSessions']();
}

export function ListShells() {
  return window['go']['main']['App']['ListShells']();
}

export function OpenFolder(arg1) {
  return window['go']['main']['App']['OpenFolder'](arg1);
}

export function OpenFolderDialog() {
  return window['go']['main']['App']['OpenFolderDialog']();
}

export function OpenWorkspace(arg1) {
  return window['go']['main']['App']['OpenWorkspace'](arg1);
}

export function OpenWorkspaceDialog() {
  return window['go']['main']['App']['OpenWorkspaceDialog']();
}

export function PinRecent(arg1, arg2) {
  return window['go']['main']['App']['PinRecent'](arg1, arg2);
}

export function ReadFile(arg1) {
  return window['go']['main']['App']['ReadFile'](arg1);
}

export function ReadFileBase64(arg1) {
  return window['go']['main']['App']['ReadFileBase64'](arg1);
}

export function RemoveRecent(arg1) {
  return window['go']['main']['App']['RemoveRecent'](arg1);
}

export function RenameFile(arg1, arg2) {
  return window['go']['main']['App']['RenameFile'](arg1, arg2);
}

export function RenameSession(arg1, arg2) {
  return window['go']['main']['App']['RenameSession'](arg1, arg2);
}

export function ResizeSession(arg1, arg2, arg3) {
  return window['go']['main']['App']['ResizeSession'](arg1, arg2, arg3);
}

export function SaveWorkspace() {
  return window['go']['main']['App']['SaveWorkspace']();
}

export function SaveWorkspaceAs(arg1) {
  return window['go']['main']['App']['SaveWorkspaceAs'](arg1);
}

export function SearchContent(arg1, arg2) {
  return window['go']['main']['App']['SearchContent'](arg1, arg2);
}

export function SearchFilename(arg1, arg2) {
  return window['go']['main']['App']['SearchFilename'](arg1, arg2);
}

export function Shutdown() {
  return window['go']['main']['App']['Shutdown']();
}

export function Startup(arg1) {
  return window['go']['main']['App']['Startup'](arg1);
}

export function StopSession(arg1) {
  return window['go']['main']['App']['StopSession'](arg1);
}

export function Subscribe(arg1) {
  return window['go']['main']['App']['Subscribe'](arg1);
}

export function ToggleHiddenFiles() {
  return window['go']['main']['App']['ToggleHiddenFiles']();
}

export function WriteFile(arg1, arg2) {
  return window['go']['main']['App']['WriteFile'](arg1, arg2);
}

export function WriteSession(arg1, arg2) {
  return window['go']['main']['App']['WriteSession'](arg1, arg2);
}
