// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddFolderToWorkspace(arg1) {
  return window['go']['main']['App']['AddFolderToWorkspace'](arg1);
}

export function CheckSyntax(arg1, arg2) {
  return window['go']['main']['App']['CheckSyntax'](arg1, arg2);
}

export function CloseWorkspace() {
  return window['go']['main']['App']['CloseWorkspace']();
}

export function CopyFile(arg1, arg2) {
  return window['go']['main']['App']['CopyFile'](arg1, arg2);
}

export function CreateAIAgent(arg1, arg2, arg3) {
  return window['go']['main']['App']['CreateAIAgent'](arg1, arg2, arg3);
}

export function CreateAgentSession(arg1, arg2, arg3) {
  return window['go']['main']['App']['CreateAgentSession'](arg1, arg2, arg3);
}

export function CreateAgentSessionFromDefinition(arg1, arg2) {
  return window['go']['main']['App']['CreateAgentSessionFromDefinition'](arg1, arg2);
}

export function CreateFile(arg1) {
  return window['go']['main']['App']['CreateFile'](arg1);
}

export function CreateShell(arg1, arg2) {
  return window['go']['main']['App']['CreateShell'](arg1, arg2);
}

export function DeleteAgentDefinition(arg1) {
  return window['go']['main']['App']['DeleteAgentDefinition'](arg1);
}

export function DeleteAgentSession(arg1) {
  return window['go']['main']['App']['DeleteAgentSession'](arg1);
}

export function DeleteFile(arg1) {
  return window['go']['main']['App']['DeleteFile'](arg1);
}

export function DeleteMCPServer(arg1) {
  return window['go']['main']['App']['DeleteMCPServer'](arg1);
}

export function ExpandPath(arg1) {
  return window['go']['main']['App']['ExpandPath'](arg1);
}

export function FetchProviderModels(arg1, arg2) {
  return window['go']['main']['App']['FetchProviderModels'](arg1, arg2);
}

export function FormatCode(arg1, arg2) {
  return window['go']['main']['App']['FormatCode'](arg1, arg2);
}

export function GenerateAICommitMessage(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['GenerateAICommitMessage'](arg1, arg2, arg3, arg4);
}

export function GetAgentSession(arg1) {
  return window['go']['main']['App']['GetAgentSession'](arg1);
}

export function GetCurrentWorkspace() {
  return window['go']['main']['App']['GetCurrentWorkspace']();
}

export function GetFileTree(arg1) {
  return window['go']['main']['App']['GetFileTree'](arg1);
}

export function GetFsChangeCount() {
  return window['go']['main']['App']['GetFsChangeCount']();
}

export function GetGitCommitDiff(arg1, arg2) {
  return window['go']['main']['App']['GetGitCommitDiff'](arg1, arg2);
}

export function GetGitCommitGraph(arg1, arg2, arg3) {
  return window['go']['main']['App']['GetGitCommitGraph'](arg1, arg2, arg3);
}

export function GetGitStatus(arg1) {
  return window['go']['main']['App']['GetGitStatus'](arg1);
}

export function GetHomeDir() {
  return window['go']['main']['App']['GetHomeDir']();
}

export function GetLLMConfig() {
  return window['go']['main']['App']['GetLLMConfig']();
}

export function GetProviderProfiles() {
  return window['go']['main']['App']['GetProviderProfiles']();
}

export function GetRecentProjects() {
  return window['go']['main']['App']['GetRecentProjects']();
}

export function GitCommit(arg1, arg2) {
  return window['go']['main']['App']['GitCommit'](arg1, arg2);
}

export function GitDiscard(arg1, arg2) {
  return window['go']['main']['App']['GitDiscard'](arg1, arg2);
}

export function GitPush(arg1) {
  return window['go']['main']['App']['GitPush'](arg1);
}

export function GitStage(arg1, arg2) {
  return window['go']['main']['App']['GitStage'](arg1, arg2);
}

export function GitUnstage(arg1, arg2) {
  return window['go']['main']['App']['GitUnstage'](arg1, arg2);
}

export function IsDir(arg1) {
  return window['go']['main']['App']['IsDir'](arg1);
}

export function ListAIAgents() {
  return window['go']['main']['App']['ListAIAgents']();
}

export function ListAgentDefinitions() {
  return window['go']['main']['App']['ListAgentDefinitions']();
}

export function ListAgentSessions() {
  return window['go']['main']['App']['ListAgentSessions']();
}

export function ListDirectory(arg1) {
  return window['go']['main']['App']['ListDirectory'](arg1);
}

export function ListLLMProviders() {
  return window['go']['main']['App']['ListLLMProviders']();
}

export function ListMCPServers() {
  return window['go']['main']['App']['ListMCPServers']();
}

export function ListMCPTools() {
  return window['go']['main']['App']['ListMCPTools']();
}

export function ListSessions() {
  return window['go']['main']['App']['ListSessions']();
}

export function ListShells() {
  return window['go']['main']['App']['ListShells']();
}

export function ListSkills() {
  return window['go']['main']['App']['ListSkills']();
}

export function MoveFile(arg1, arg2) {
  return window['go']['main']['App']['MoveFile'](arg1, arg2);
}

export function OpenFileDialog() {
  return window['go']['main']['App']['OpenFileDialog']();
}

export function OpenFolder(arg1) {
  return window['go']['main']['App']['OpenFolder'](arg1);
}

export function OpenFolderDialog() {
  return window['go']['main']['App']['OpenFolderDialog']();
}

export function OpenInFinder(arg1) {
  return window['go']['main']['App']['OpenInFinder'](arg1);
}

export function OpenNewWindow(arg1) {
  return window['go']['main']['App']['OpenNewWindow'](arg1);
}

export function OpenWorkspace(arg1) {
  return window['go']['main']['App']['OpenWorkspace'](arg1);
}

export function OpenWorkspaceDialog() {
  return window['go']['main']['App']['OpenWorkspaceDialog']();
}

export function PinRecent(arg1, arg2) {
  return window['go']['main']['App']['PinRecent'](arg1, arg2);
}

export function ReadFile(arg1) {
  return window['go']['main']['App']['ReadFile'](arg1);
}

export function ReadFileBase64(arg1) {
  return window['go']['main']['App']['ReadFileBase64'](arg1);
}

export function RemoveFolderFromWorkspace(arg1) {
  return window['go']['main']['App']['RemoveFolderFromWorkspace'](arg1);
}

export function RemoveRecent(arg1) {
  return window['go']['main']['App']['RemoveRecent'](arg1);
}

export function RenameFile(arg1, arg2) {
  return window['go']['main']['App']['RenameFile'](arg1, arg2);
}

export function RenameSession(arg1, arg2) {
  return window['go']['main']['App']['RenameSession'](arg1, arg2);
}

export function ResizeSession(arg1, arg2, arg3) {
  return window['go']['main']['App']['ResizeSession'](arg1, arg2, arg3);
}

export function ResolvePath(arg1) {
  return window['go']['main']['App']['ResolvePath'](arg1);
}

export function RespondAgentApproval(arg1, arg2, arg3) {
  return window['go']['main']['App']['RespondAgentApproval'](arg1, arg2, arg3);
}

export function SaveAgentDefinition(arg1) {
  return window['go']['main']['App']['SaveAgentDefinition'](arg1);
}

export function SaveLLMProfile(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['SaveLLMProfile'](arg1, arg2, arg3, arg4);
}

export function SaveMCPServer(arg1) {
  return window['go']['main']['App']['SaveMCPServer'](arg1);
}

export function SaveProviderProfiles(arg1) {
  return window['go']['main']['App']['SaveProviderProfiles'](arg1);
}

export function SaveWorkspace() {
  return window['go']['main']['App']['SaveWorkspace']();
}

export function SaveWorkspaceAs(arg1) {
  return window['go']['main']['App']['SaveWorkspaceAs'](arg1);
}

export function SaveWorkspaceDialog() {
  return window['go']['main']['App']['SaveWorkspaceDialog']();
}

export function SearchContent(arg1, arg2) {
  return window['go']['main']['App']['SearchContent'](arg1, arg2);
}

export function SearchContentWithOptions(arg1) {
  return window['go']['main']['App']['SearchContentWithOptions'](arg1);
}

export function SearchFilename(arg1, arg2) {
  return window['go']['main']['App']['SearchFilename'](arg1, arg2);
}

export function SearchFilenameWithOptions(arg1) {
  return window['go']['main']['App']['SearchFilenameWithOptions'](arg1);
}

export function SearchSymbols(arg1, arg2) {
  return window['go']['main']['App']['SearchSymbols'](arg1, arg2);
}

export function SearchSymbolsWithOptions(arg1) {
  return window['go']['main']['App']['SearchSymbolsWithOptions'](arg1);
}

export function SendAgentMessage(arg1, arg2, arg3) {
  return window['go']['main']['App']['SendAgentMessage'](arg1, arg2, arg3);
}

export function SetActiveModel(arg1, arg2) {
  return window['go']['main']['App']['SetActiveModel'](arg1, arg2);
}

export function Shutdown() {
  return window['go']['main']['App']['Shutdown']();
}

export function Startup(arg1) {
  return window['go']['main']['App']['Startup'](arg1);
}

export function StopSession(arg1) {
  return window['go']['main']['App']['StopSession'](arg1);
}

export function Subscribe(arg1) {
  return window['go']['main']['App']['Subscribe'](arg1);
}

export function ToggleAgentTask(arg1, arg2, arg3) {
  return window['go']['main']['App']['ToggleAgentTask'](arg1, arg2, arg3);
}

export function ToggleHiddenFiles() {
  return window['go']['main']['App']['ToggleHiddenFiles']();
}

export function UpdateAgentSession(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['UpdateAgentSession'](arg1, arg2, arg3, arg4, arg5);
}

export function WriteFile(arg1, arg2) {
  return window['go']['main']['App']['WriteFile'](arg1, arg2);
}

export function WriteSession(arg1, arg2) {
  return window['go']['main']['App']['WriteSession'](arg1, arg2);
}
